# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright (c) 2026 Hygon Information Technology Co., Ltd.
"""Literal-only HCU CI test registry consumed by static AST tooling.

This module is data expressed as calls. CI parses it without importing tests or
the HCU runtime. ``est_time`` is seconds and is used for deterministic LPT
partitioning; update it from observed job artifacts when runtimes drift.
"""

from __future__ import annotations

# This source is intentionally not imported. The CI control plane parses these
# calls as literals, so adding imports or runtime-generated values is forbidden.


register_hcu_ci(
    job="accuracy-gfx936",
    target="tests/accuracy/test_hcu_kernel_accuracy.py",
    est_time=900,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_hcu_kernel_accuracy.py",
    est_time=900,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_aiter_silu_and_mul.py",
    est_time=300,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_aiter_batched_gemm_bf16.py",
    est_time=180,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_lightop_mla_concat_accuracy.py",
    est_time=120,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_lightop_sqrtsoftplus_gate.py",
    est_time=120,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_lightop_qwen_rmsnorm_gated_accuracy.py",
    est_time=120,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_moe_align_fallback_graph.py",
    est_time=120,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_lightop_w16a16_moe_accuracy.py",
    est_time=180,
)
register_hcu_ci(
    job="accuracy-gfx938",
    target="tests/accuracy/test_unified_aiter_moe_operator.py",
    est_time=330,
)

register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/patch/test_base_linear_parameter.py",
    est_time=180,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/runtime_patch/test_glm53_channel_fp8.py",
    est_time=60,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/patch/test_clean_process_bootstrap.py",
    est_time=300,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/patch/test_plugin_lifecycle.py",
    est_time=300,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/patch/test_runtime_callbacks.py",
    est_time=180,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/runtime_patch/test_platform_framework_opt.py",
    est_time=120,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/runtime_patch/test_quant_gemm_aiter.py",
    est_time=180,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/runtime_patch/test_worker_framework_opt.py",
    est_time=180,
)
register_hcu_ci(
    job="contract-hcu-gfx936",
    target="tests/runtime_patch/test_lightop_categorized_api.py",
    est_time=60,
)

register_hcu_ci(
    job="integration-smoke-gfx938",
    target="tests/integration/graph/test_qwen35_9b_graph_parity.py",
    est_time=900,
)
register_hcu_ci(
    job="integration-smoke-gfx938",
    target="tests/integration/lora/test_qwen3_4b_lora_switching.py",
    est_time=1200,
)
register_hcu_ci(
    job="integration-smoke-gfx938",
    target="tests/integration/models/test_qwen35_9b_smoke.py",
    est_time=900,
)
register_hcu_ci(
    job="integration-smoke-gfx938",
    target="tests/integration/server/test_evalscope_report_threshold.py",
    est_time=30,
)

register_hcu_ci(
    job="qwen35-smoke",
    target=(
        "tests/integration/models/test_qwen35_9b_smoke.py::"
        "test_qwen35_9b_greedy_generation_smoke"
    ),
    est_time=900,
)
register_hcu_ci(
    job="qwen35-graph",
    target=(
        "tests/integration/graph/test_qwen35_9b_graph_parity.py::"
        "test_qwen35_9b_eager_graph_token_parity"
    ),
    est_time=1200,
)
register_hcu_ci(
    job="engine-features",
    target="tests/integration/features/test_qwen3_4b_engine_features.py",
    est_time=2400,
)
register_hcu_ci(
    job="lora",
    target=(
        "tests/integration/lora/test_qwen3_4b_lora_switching.py::"
        "test_qwen3_4b_lora_adapter_switching"
    ),
    est_time=1800,
)
register_hcu_ci(
    job="spec-decode",
    target=(
        "tests/integration/spec_decode/test_llama2_7b_eagle_parity.py::"
        "test_llama2_7b_eagle_spec_decode_token_parity"
    ),
    est_time=2400,
    disabled=(
        "times out on the single-card gfx938 PR runner; keep out of required "
        "HCU gating until EAGLE startup/runtime is stabilized"
    ),
)
register_hcu_ci(
    job="spec-decode",
    target=(
        "tests/integration/spec_decode/test_llama2_7b_eagle_parity.py::"
        "test_qwen35_4b_mtp_spec_decode_token_parity"
    ),
    est_time=2400,
)
register_hcu_ci(
    job="mamba-smoke",
    target=(
        "tests/integration/models/test_falcon_mamba_smoke.py::"
        "test_falcon_mamba_tiny_real_prefill_decode_smoke"
    ),
    est_time=1200,
    disabled=(
        "required Falcon Mamba model is unavailable in the public and "
        "parastor CI model roots"
    ),
)
register_hcu_ci(
    job="kv-transfer",
    target=(
        "tests/integration/kv_transfer/test_example_connector_smoke.py::"
        "test_example_connector_kv_transfer_smoke"
    ),
    est_time=1800,
)
register_hcu_ci(
    job="qwen35-tp-ep",
    target=(
        "tests/integration/parallel/test_tp_ep_models.py::"
        "test_qwen35_35b_a3b_tp_ep_smoke"
    ),
    est_time=7200,
)
register_hcu_ci(
    job="deepseek-tp-ep",
    target=(
        "tests/integration/parallel/test_tp_ep_models.py::"
        "test_deepseek_r1_channel_int8_tp_ep_smoke"
    ),
    est_time=10800,
)
register_hcu_ci(
    job="qwen25-models",
    target=(
        "tests/integration/models/test_qwen25_models.py::"
        "test_qwen25_vl_3b_image_mrope_smoke"
    ),
    est_time=1800,
)
register_hcu_ci(
    job="qwen25-models",
    target=(
        "tests/integration/server/test_qwen25_server_smoke.py::"
        "test_qwen25_15b_openai_server_smoke"
    ),
    est_time=1800,
)
register_hcu_ci(
    job="qwen3-pooling",
    target="tests/integration/models/test_qwen3_pooling_models.py",
    est_time=1800,
)
register_hcu_ci(
    job="qwen3-pooling",
    target=(
        "tests/integration/server/test_qwen3_pooling_server.py::"
        "test_qwen3_embedding_06b_openai_embeddings_server_smoke"
    ),
    est_time=1800,
)
register_hcu_ci(
    job="qwen3-pooling",
    target=(
        "tests/integration/server/test_qwen3_pooling_server.py::"
        "test_qwen3_reranker_score_and_rerank_server_smoke"
    ),
    est_time=1800,
    disabled=(
        "required sequence-classification reranker model is unavailable in "
        "the public and parastor CI model roots"
    ),
)
register_hcu_ci(
    job="qwen3-protocol",
    target="tests/integration/server/test_qwen3_protocol_features.py",
    est_time=2700,
)
register_hcu_ci(
    job="qwen35-gsm8k",
    target=(
        "tests/integration/server/test_evalscope_qwen35_9b_gsm8k.py::"
        "test_qwen35_9b_gsm8k_evalscope_server"
    ),
    est_time=3600,
)
register_hcu_ci(
    job="qwen3-vl-mmmu",
    target=(
        "tests/integration/server/test_evalscope_qwen3_vl_8b_mmmu.py::"
        "test_qwen3_vl_8b_mmmu_evalscope_server"
    ),
    est_time=5400,
)
register_hcu_ci(
    job="qwen3-8b-gsm8k",
    target=(
        "tests/integration/server/test_evalscope_qwen3_8b_gsm8k.py::"
        "test_qwen3_8b_gsm8k_evalscope_server"
    ),
    est_time=5400,
)
register_hcu_ci(
    job="qwen38-flash-next-humaneval",
    target=(
        "tests/integration/server/test_evalscope_qwen38_flash_next_humaneval.py::"
        "test_qwen38_flash_next_humaneval_evalscope_server"
    ),
    est_time=10800,
)
register_hcu_ci(
    job="qwen38-flash-next-int8-pp2-tp4-humaneval",
    target=(
        "tests/integration/server/"
        "test_evalscope_qwen38_flash_next_int8_pp2_tp4_humaneval.py::"
        "test_qwen38_flash_next_int8_pp2_tp4_humaneval_evalscope_server"
    ),
    est_time=10800,
)
register_hcu_ci(
    job="deepseek-gsm8k",
    target=(
        "tests/integration/server/test_evalscope_deepseek_r1_gsm8k.py::"
        "test_deepseek_r1_channel_fp8_gsm8k_evalscope_server"
    ),
    est_time=14400,
)
register_hcu_ci(
    job="glm52-pcp",
    target="tests/integration/models/test_glm52_pcp_mrv2.py",
    est_time=14400,
    disabled=(
        "required GLM-5.2 model is unavailable in the public and parastor CI "
        "model roots"
    ),
)
register_hcu_ci(
    job="glm52-pcp",
    target="tests/integration/server/test_evalscope_glm52_pcp_humaneval.py",
    est_time=14400,
    disabled=(
        "required GLM-5.2 model is unavailable in the public and parastor CI "
        "model roots"
    ),
)
register_hcu_ci(
    job="glm53-flash-channel-fp8-humaneval",
    target=(
        "tests/integration/server/"
        "test_evalscope_glm53_flash_channel_fp8_humaneval.py::"
        "test_glm53_flash_channel_fp8_humaneval_evalscope_server"
    ),
    est_time=14400,
)
register_hcu_ci(
    job="single-node-topology",
    target="tests/distributed/single_node/test_topology_contracts.py",
    est_time=60,
)
